#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use Benchmark::Command;

Benchmark::Command::run(0, {
    'perl'              => [$^X, "-I$Bin/../lib", "-e1"],
    'load_ciod'         => [$^X, "-I$Bin/../lib", "-MConfig::IOD", "-e", 1],
    'read_empty_iod'    => [$^X, "-I$Bin/../lib", "-MConfig::IOD", "-e", '$reader = Config::IOD->new; $doc = $reader->read_string("")'],
});
